### PR TITLE
Make extracted tensors backed by flat arrays

### PR DESCRIPTION
**Pull request by vvvvalvalval**
… for performance. Also some minor refactoring.

## Purpose
For performance, callers of Magellan will prefer tensors backed by a flat array, rather than the nested arrays provided by the current implementation. This PR makes this the default.

It will in particular make GridFire faster, as it will less often need to copy to a flat-array tensor.

## Related Issues
GRID1-436

## Submission Checklist
- [ ] ~~Commits include the JIRA issue and the `#review` hashtag (e.g. `MAG-### #review <comment>`)~~ 
- [x] Code passes linter rules (`clj-kondo --lint src`)
- [x] Tests pass (`clj -M:test`)

## Testing
Magellan has no test coverage for this; however, GridFire does, and the GridFire tests still pass when changing its Magellan deps coordinate to this new commit.

### CODE REVIEW

**Comment by lambdatronic** [comment]
# src/magellan/raster/impl/interop.clj
- Note: While this all looks logically correct and does precisely what
  the old code did, it is quite a bit more verbose. I'm not sure I'd
  see that as a feature since more lines of code mean more lines to
  debug in the future. Note that all of this could be just as easily
  (and more compactly) represented without multimethods (or macros)
  like so:

```clojure
(defn tensor-backing-array [target-dtype arr-length]
  (let [arr-length (int arr-length)]
    (case target-dtype
      :int32   (int-array    arr-length)
      :float32 (float-array  arr-length)
      :float64 (double-array arr-length))))

(defn get-samples [target-dtype ^Raster raster x y w h b]
  (let [w            (int w)
        h            (int h)
        chunk-length (* w h)
        chunk-array  (tensor-backing-array target-dtype chunk-length)]
    (.getSamples raster (int x) (int y) w h (int b) chunk-array)))
```

  Note, of course, with so little code, there's hardly a reason for a
  new namespace. We could just as easily add these two functions to
  `magellan.raster.inspect`.

# src/magellan/raster/inspect.clj
- 137: Redundant primitive typecast for `w` and `h`.

**Comment by vvvvalvalval** [comment]
@lambdatronic changed as you suggested, except for your suggestion reimplementation of `get-samples`, which would:
1. cause a JVM reflection call (cannot disambiguate overloads of `.getSamples()`)
2. make a misleading use of the name `tensor-backing-array`, since the returned array won't be used for backing the tensor, but as a data-transfer buffer.

FYI, the rationale behind those code structure choices was:

> it is quite a bit more verbose. I'm not sure I'd
see that as a feature since more lines of code mean more lines to
debug in the future. Note that all of this could be just as easily
(and more compactly) represented without multimethods (or macros)
like so:

I can relate. I was only aiming from simple rather than easy (in the seminal conference talk, multimethods are recommended over close-ended switch statements for this very reason).

> Note, of course, with so little code, there's hardly a reason for a
new namespace.

Personally what I like about a separate namespace is that it makes the absence of complecting more evident. It also tends to reduce the necessity for refactoring if the functionality turns out to be needed in other places.

**Comment by lambdatronic** [comment]
Good catch on the JVM reflection call. I had sketched that code out as
an example without testing it. Silly me.

> I can relate. I was only aiming from simple rather than easy (in the
> seminal conference talk, multimethods are recommended over close-ended
> switch statements for this very reason).

Yes, I thought about this very point (and talk) when I was making my
recommendation. However, Rich's reason for promoting multimethods over
`case`/`cond` was to keep the code open to arbitrary extension in the
future. In this case, we are just wrapping `.getSamples` though, and
its set of supported input argument types is both small and rarely
changed. As a result, it seemed to me that the long-term benefit of
being able to add support for new `.getSamples` input types (if any
are ever added in GeoTools) was outweighed by the immediate (and
persistent) benefit of having much less code to read, maintain, test,
and debug in the future. Just my 2c. YMMV

> Personally what I like about a separate namespace is that it makes
> the absence of complecting more evident. It also tends to reduce the
> necessity for refactoring if the functionality turns out to be
> needed in other places.

I'm in favor of additional namespaces when they encapsulate some new
set of ideas or solve the diamond problem when sharing vars between
multiple namespaces. On the other hand, creating new namespaces means
marking more functions as public. In a strictly accretive programming
workflow, keeping the set of public functions to a minimum is very
helpful since they become the unchangeable (or at least
hard-to-change) API of your library. Conversely, it is safe to change,
rename, or reimplement private functions as much as you might like,
provided that the public functions that use them still maintain
consistent behavior between software versions.

Again, it's just a matter of deciding between competing priorities.

If I haven't said it enough though, I think your work is of very high
quality. Keep on writing great code, Val. And keep on defending the
principles that guide it. I promise that I am also thinking about
these design decisions on my end. I suspect we agree much more often
than we disagree.

**Comment by vvvvalvalval** [comment]
@lambdatronic thanks for taking the time, and for the kind words. The appreciation is reciprocal, and I think we have a good process here.

**Pull request merged**
