### PR TITLE
Added new raster inspection functions to magellan.raster.inspect.

### PR DESCRIPTION
**Pull request by lambdatronic**
----

#

### CODE REVIEW

**Comment by Kcheung42** [comment]
magellan.raster.inspect
- Line 63: Align values in map
- Line 72: Would using `case` be more idiomatic here?
- Line 83:  Align values (not sure the best way to align with long destructuring. Would this be better? Could we come up with a style guide for this?

```
(let [image                  (:image raster)
      data                   (.getData image)
      {:keys [height width
              bands origin]} (describe-image image)
      {min-x :x min-y :y}    origin
      typed-array            (get-typed-array (.getDataType (.getDataBuffer data)))]
    ...)
```

- Line 127: remove assertion since `:matrix` is no longer in our map

Everything else Looks good to me (LGTM) other than needing tests.

**Comment by Kcheung42** [comment]
* Line 73 Should this be byte-array
* Line 74-75 Should this be short-array

**Comment by lambdatronic** [comment]
magellan.raster.inspect:
- Line 72: Would using `case` be more idiomatic here?

No. `case` only works with unevaluated match values, so `DataBuffer/TYPE_BYTE` will be read as a symbol, not evaluated to its numeric value, which is needed to match the value in `data-buffer-type`.

- Line 73 Should this be byte-array
- Line 74-75 Should this be short-array

See the comment note above get-typed-array.

**Comment by Kcheung42** [comment]
As investigated and discussed. The following needs to be commented out to prevent NULL pointer exception.
```
(defn describe-band [^GridSampleDimension band]
  {:description (str (.getDescription band))
   :type        (str (.getSampleDimensionType band))
   ;; FIXME: missing band info when writing raster to disk via matrix-to-raster
   ;; :min         (.getMinimum (.getRange band))
   ;; :max         (.getMaximum (.getRange band))
   :no-data     (.getNoDataValues band)
   :offset      (.getOffset band)
   :scale       (.getScale band)
   :units       (.getUnits band)
   ;; FIXME: missing band info when writing raster to disk via matrix-to-raster
   ;; :categories  (reduce (fn [acc cat]
   ;;                        (let [range (.getRange cat)]
   ;;                          (assoc acc
   ;;                                 (str (.getName cat))
   ;;                                 {:min (.getMinimum range)
   ;;                                  :max (.getMaximum range)})))
   ;;                      {}
   ;;                      (.getCategories band))
   })
   ```

**Pull request merged**
