### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by Kcheung42**

### CODE REVIEW

**Comment by lambdatronic** [comment]
deps.edn:
- Line 1: Remove "test" from :paths and add it to :extra-paths under
  the :test alias. Doing this should prevent :make-jar from including
  the test code and data files in the generated JAR. GeoTIFFs can be
  quite large and should not be pushed to Clojars.
- Lines 22-27: Reformat the :test alias like so:
```clojure
:test {:extra-paths ["test"]
       :extra-deps  {com.cognitect/test-runner {:git/url "https://github.com/cognitect-labs/test-runner.git"
                                                :sha     "209b64504cb3bd3b99ecfec7937b358a879f55c1"}}
       :main-opts   ["-m" "cognitect.test-runner"]}
```

core.clj:
- Line 116: Remove extra blank line.
- Line 151-181: Remove the comment block as it includes
  system-specific filenames. The test suite should include examples of
  all of these kinds of operations.

core_test.clj:
- Line 1: Single element namespaces are strongly discouraged in
  Clojure as they can lead to namespace collisions with other
  libraries within a running JVM. Move test/core_test.clj to
  test/magellan/core_test.clj and change its namespace to
  `magellan.core-test`.
- Lines 2,3: Don't use `:refer :all` as this makes symbol name tracing
  difficult for other developers. Please explicitly :refer symbols
  from other namespaces or use :as for a short-hand namespace alias.
- Line 6: Move first Java import onto the line containing `:import`.
- Lines 25,26,39,43: `clojure.java.io` -> `io`
- Line 30: Fixures -> Fixtures
- Line 11,13,*: When making comment blocks for each code section, use
  `;;----` rather than `;; ---`. Keep a space before comment text
  (e.g., `;; Utils`).
- Lines *: Only leave one blank line between `def*` forms.
- Lines *: Be consistent with placing your function args either on the
  same line as the function name or on the line following the function
  name. Try not to vary this unless there is a special reason for that
  function.

**Comment by Kcheung42** [comment]
> Line 1: Remove "test" from :paths and add it to :extra-paths under
> the :test alias. Doing this should prevent :make-jar from including
> the test code and data files in the generated JAR. GeoTIFFs can be
> quite large and should not be pushed to Clojars.

For some reason doing this interferes with `cider-test`. Testing with the Alias is fine though. Will have to look into.

**Comment by lambdatronic** [comment]
deps.edn:
- Lines 18-20: Revert the AOT compilation change to the :make-jar
  alias. There is no -main function in magellan.core, so this won't
  work. Also, we don't want to AOT compile an open source library.
- Lines 24-30: Reformat the :test alias like so:
```clojure
:test {:extra-paths ["test"]
       :extra-deps  {com.cognitect/test-runner {:git/url "https://github.com/cognitect-labs/test-runner.git"
                                                :sha     "209b64504cb3bd3b99ecfec7937b358a879f55c1"}}
       :main-opts   ["-m" "cognitect.test-runner"]}
```

core_test.clj:
- Line 2: Don't use `:refer :all` as this makes symbol name tracing
  difficult for other developers. For clojure.test, please explicitly
  refer the symbols that you intend to use (e.g., `:refer [deftest is use-fixtures]`).
- Line 3: Please require our magellan.* namespaces last in the require
  list. This is just an in-house coding convention.
- Lines 13,27: Remove extra blank lines
- Line 19: Be consistent with placing your function args either on the
  same line as the function name or on the line following the function
  name. Try not to vary this unless there is a special reason for that
  function.
- Lines 38,42: `clojure.java.io` -> `io`

**Comment by lambdatronic** [comment]
core.clj:
- Line 83: `(io/resource filename)` -> `(io/as-url (io/file filename))`

core_test.clj:
- *: Since all of these functions are extremely simple and don't need
  (or have) docstrings, move the args onto the same line as the
  function name.
- Lines 5,8: These Java libs are not used.
- Line 7: ReferencingFactoryFinder is not used.
- Line 10: Add this section before Utils:
```clojure
;;-----------------------------------------------------------------------------
;; Config
;;-----------------------------------------------------------------------------

(def input-dirname  "test/data/")
(def output-dirname "test/output/")
```
- Lines 14-16: Drop file-path and add these function to the Utils section:
```clojure
(defn in-file-path [filename]
  (str input-dirname filename))

(defn out-file-path [filename]
  (str output-dirname filename))
```
- Line 22: Replace `setup-once` with this code:
```clojure
(defn make-directory [dirname]
  (.mkdir (io/file dirname)))
```
- Lines 22-29: Move `make-directory` and `delete-directory` to the Utils section.
- Lines 31-33: Drop `teardown-once`.
- Lines 35-39: Replace `fixture-once` with a more clearly named function using the new utility functions:
```clojure
(defn with-temp-output-dir [test-fn]
  (make-directory output-dirname)
  (test-fn)
  (delete-directory output-dirname))
```
- Line 41: `(use-fixtures :once with-temp-output-dir)`
- Lines 49,55,92,132,133,167: Rename `file-path` to `in-file-path`.
- Line 54: "Writing raster to file" (for consistency with read-raster-test's message).
- Lines 56,57: "test/output/SRS-EPSG-3857.tif" -> `(out-file-path "SRS-EPSG-3857.tif")`
- Lines 81,85: descrepancies -> discrepancies
- Lines 93,94,103,104: No commas in Clojure.
- Line 120: `(:crs rast)` has already been tested above.
- Line 131: "Reprojecting a raster" 
- Line 136: `samp-rast` -> `reprojected-rast`
- Line 138: Use `not=`.
- Line 139: new -> New
- Line 142: Move `new-crs` to previous line.
- Line 143: should -> Should
- Line 146: resampling -> Resampling
- Lines 147,148: No commas in Clojure.
- Line 153: Use `matrix2` rather than repeating the `(repeat ...)` form.
- Lines 150,152: matrix -> matrix1
- Lines 152,154,157: source-rast -> rast1
- Lines 153,154,158,162: target-rast -> rast2
- Line 155: Remove extra blank line.
- Line 157: Use `not=`.
- Line 159: resolution -> Resolution
- Line 163: resampled -> Resampled
- Line 166: cropping -> Cropping
- Lines 172: Include a blank line after let bindings for consistency with your other tests.
- Line 174: Use `not=`.
- Line 177: Needs `testing` form.
- Line 178: "data/sample_projections.properties" -> `(in-file-path "sample_projections.properties")`
- Lines 179: Include a blank line after let bindings for consistency with your other tests.

**Pull request merged**
